### ISSUE TITLE
Caradoc does not accept incremental update

### ISSUE THREAD

**Issue by Chimrod** [ANSSI-FR/caradoc#1]
Pdf with incremental update are not accepted by caradoc. Incremental update contains multiple xref, each one pointing to a previous (overrided one) througth the « Prev » keyword in the dictionnary.

This document is a valid one, but is refused by caradoc :

```pdf
%PDF-1.1

1 0 obj
<<
 /Type /Catalog
 /Outlines 2 0 R
 /Pages 3 0 R
>>
endobj

2 0 obj
<<
 /Type /Outlines
 /Count 0
>>
endobj

3 0 obj
<<
 /Type /Pages
 /Kids [4 0 R]
 /Count 1
>>
endobj

4 0 obj
<<
 /Type /Page
 /Parent 3 0 R
 /MediaBox [0 0 612 792]
 /Contents 5 0 R
 /Resources <<
             /ProcSet [/PDF /Text]
             /Font << /F1 6 0 R >>
            >>
>>
endobj

5 0 obj
<<
 /Length 89
 /Filter /ASCII85Decode
>>
stream
6<#'\7PQ#@1a#b0+>GQ(+?(u.+B2ko-rakk+E1b1F)Yf5@<6!&BlbCgDI[]uD.RU,@;I&dE+EC!ATK:C<,*OE;u~>
endstream
endobj

6 0 obj
<<
 /Type /Font
 /Subtype /Type1
 /Name /F1
 /BaseFont /Helvetica
 /Encoding /MacRomanEncoding
>>
endobj

xref
0 7
0000000000 65535 f
0000000012 00000 n
0000000089 00000 n
0000000145 00000 n
0000000214 00000 n
0000000419 00000 n
0000000594 00000 n
trailer
<<
 /Size 7
 /Root 1 0 R
>>
startxref
718
%%EOF

5 0 obj
<<
 /Length 89
 /Filter /ASCII85Decode
>>
stream
6<#'\7PQ#@1a#b0+>GQ(+?(u.+B2ko-rakk+E1b1F)Yf5@<6!&BlbD!=BJ[-=BJ[-=BJ[-=BJ[-=BI!p<,*OE;u~>
endstream
endobj

xref
0 1
0000000000 65535 f
5 1
0000000935 00000 n
trailer
<<
 /Size 7
 /Root 1 0 R
 /Prev 718
>>
startxref
1110
%%EOF
```

**Comment by gendx** [comment]
Correct, the strict parser does not accept incremental updates. You may want to clean up the file first :

```
caradoc cleanup original.pdf --out clean.pdf
caradoc stats --strict clean.pdf
```

We will clarify this on the README, but the strict parser does not accept such constructs as incremental updates, because we wanted to avoid complex parsing steps (that are less reliable). Have a look at our [formal grammar](https://github.com/ANSSI-FR/caradoc/blob/master/doc/grammar/grammar.pdf) for the strict parser.
We will discuss these choices in more detail during our presentation at the [LangSec workshop](http://spw16.langsec.org/).

To come back to problems caused by incremental updates, you can have a look at the paper of Bogk and Schöpl : [http://spw14.langsec.org/papers.html](http://spw14.langsec.org/papers.html).
Also, as your file rightly suggests, incremental updates can cause privacy issues by "masking" some content that is in fact not removed at all. The `cleanup` tool of caradoc strips off unused objects to avoid this kind of problem.

**Comment by Chimrod** [comment]
I know that the document mask some ressources (this is why this pdf is an interesting resource), but this is still a valid document. I first thought you wanted to write a tool for checking if a document is a valid one or not…

(I have already written my own cleanup for such case, which also give me a graphviz representation for a document)

Do you plan to support object streams ? Now most of the document which pdf version >1.5 uses object streams reject such structures would exclude most of the document from real word

**Comment by gendx** [comment]
Actually, we implemented two parsers :
- a strict one that has a simple grammar (without *incremental updates* or *object streams*) ;
- a relaxed one that is more complex and handle the common structures found in the wild (including *incremental updates*, *object streams*, *cross-reference streams* and *hybrid reference files*).

The relaxed parser is notably used for our `cleanup` tool, but you can still use it to validate (less strictly) PDF files, by checking the exit code of the `stats` command (without the `--strict` parameter) :
```
caradoc stats file.pdf
```

The relaxed parser will complain if you have an invalid structure such as a loop in incremental updates (contrary to most parsers in PDF readers). So it performs some kind of validation, but given its complexity it is more prone to bugs (as all complex parsers are).
This is why we also proposed a stricter grammar, along with an associated parser.

**Comment by Chimrod** [comment]
Thanks a lot for your explanation. I'll continue my tests with caradoc. Do you plan to check all the pdf structures ?
