### ISSUE TITLE
Invalid integer overflow

### ISSUE THREAD

**Issue by Chimrod** [ANSSI-FR/caradoc#4]
This dictionnary 

```pdf
152175 0 obj
<<
/XHeight 530
/ItalicAngle 0
/FontBBox [0 -197 824 728]
/Flags 4
/FontFile2 186584 0 R
/Type /FontDescriptor
/FontName /YZUKMF+Arial-BoldMT
/Ascent 728
/CapHeight 728
/Descent -197
/StemV -2147483648
/MissingWidth 750
>>
```

Cause this error : Lexing error at offset 251180310 [0xef8b516] : integer error : integer overflow !

But according the pdf reference, the minimal integer value is « -2,147,483,648 Smallest integer value; equal to −2^31. »

What is the minimal integer value accepted by caradoc ?

**Comment by gendx** [comment]
You are right, we were a bit too much restrictive and only accepted integers in +-(2^31 - 1). I made a patch to extend the minimum to -2^31.

However, your example seems a bit contrived because according to the PDF reference (section 9.8.1), the **/StemV** field should be a thickness (so one would not expect a negative integer):

> (Required, except for Type 3 fonts) The thickness, measured
> horizontally, of the dominant vertical stems of glyphs in the font.

 If it was not hand-crafted, do you know which software produced this PDF?

**Comment by Chimrod** [comment]
The document is the result of concatenation from many differents mails. I will check if I still have the source from this page.

This value depends to the pdf implementation, and is not related with the pdf structure itself. Idealy, this value should be defined in a « adobe.profile » (and this allow to check a document against differents profile : konica, xerox )… The project gives me many ideas !
